import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static const Map<String, Map<String, String>> _localizedValues = {
    'fr': {
      'app.title': 'Trip Builder',
      'nav.home': 'Accueil',
      'nav.dossiers': 'Dossiers',
      'nav.profile': 'Profil',
      'nav.settings': 'Paramètres',
      'nav.logout': 'Déconnexion',
      'settings.title': 'Paramètres',
      'settings.preferences': 'Préférences',
      'settings.application': 'Application',
      'settings.support': 'Support',
      'settings.language': 'Langue',
      'settings.change_language': 'Changer la langue de l\'application',
      'settings.notifications': 'Notifications',
      'settings.notifications_desc': 'Configurer les alertes',
      'settings.downloads': 'Téléchargements',
      'settings.downloads_desc': 'Gérer les documents hors ligne',
      'settings.security': 'Sécurité',
      'settings.security_desc': 'Changer le mot de passe',
      'settings.theme': 'Thème',
      'settings.theme_desc': 'Mode sombre/clair',
      'settings.help': 'Aide',
      'settings.help_desc': 'Support et FAQ',
      'settings.about': 'À propos',
      'settings.about_desc': 'Version et informations',
      'greet.hello': 'Bonjour',
      'dashboard.subtitle': 'Voici le résumé de votre voyage.',
      'documents.title': 'Documents & Itinéraire',
      'documents.subtitle': 'Gérez vos documents de voyage',
      'profile.title': 'Mon Profil',
      'profile.subtitle': 'Consultez vos informations',
      'common.retry': 'Réessayer',
      'common.loading': 'Chargement...',
      'error.load_failed': 'Erreur lors du chargement des données',
      'error.generic': 'Erreur',
      'dashboard.no_active_title': 'Aucun voyage actif trouvé',
      'dashboard.no_active_subtitle':
          'Aucun voyage actif n\'a été trouvé pour vous',
      'dashboard.trip_type': 'Voyage organisé',
      'info.client': 'Client',
      'info.email': 'Email',
      'info.phone': 'Téléphone',
      'trip.program': 'Programme du voyage',
      'profile.active_traveler': 'Voyageur actif',
      'profile.active_trips': 'Voyages Actifs',
      'profile.days': 'Jours',
      'profile.folders': 'Dossiers',
      'profile.last_active_trip': 'Dernier voyage actif',
      'dossiers.results_days': '{count} jour{plural} trouvé{plural}',
      'dossiers.filtered': 'Filtré',
      'dossiers.id': 'ID',
      'dossiers.subfolders_count': '{count} dossier{plural}',
      'dossiers.docs_suffix': 'docs',
      'download.preparing': 'Préparation du téléchargement...',
      'download.unavailable':
          'Impossible d\'accéder au dossier de téléchargement',
      'download.completed': 'Fichier téléchargé: {file}',
      'download.open_folder_fail':
          'Impossible d\'ouvrir le dossier tripbuilder',
      'download.alt_try': 'Tentative de téléchargement alternatif...',
      'share.preparing': 'Préparation du partage...',
      'share.success': 'Document partagé avec succès',
      'share.error': 'Erreur lors du partage : {error}',
      'share.alt_error': 'خطأ في المشاركة البديلة: {error}',
      'auth.logout': 'Déconnexion',
      'auth.logout_confirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'password.screen_title': 'Sécurité du compte',
      'password.security_tip':
          'Pour votre sécurité, veuillez définir un nouveau mot de passe',
      'password.change_title': 'Modifier le mot de passe',
      'password.current': 'Mot de passe actuel',
      'password.current_hint': 'Entrez votre mot de passe actuel',
      'password.new': 'Nouveau mot de passe',
      'password.new_hint': 'Choisissez un mot de passe sécurisé',
      'password.confirm': 'Confirmer le nouveau mot de passe',
      'password.confirm_hint': 'Répétez votre nouveau mot de passe',
      'password.error_current_required':
          'Veuillez saisir votre mot de passe actuel',
      'password.error_new_required': 'Veuillez saisir un nouveau mot de passe',
      'password.error_min_length':
          'Le mot de passe doit contenir au moins 6 caractères',
      'password.error_confirm_required':
          'Veuillez confirmer le nouveau mot de passe',
      'password.error_mismatch': 'Les mots de passe ne correspondent pas',
      'password.changing': 'Modification en cours...',
      'password.confirm_change': 'Confirmer le changement',
      'password.changed_success': 'Mot de passe modifié avec succès',
    },
    'en': {
      'app.title': 'Trip Builder',
      'nav.home': 'Home',
      'nav.dossiers': 'Folders',
      'nav.profile': 'Profile',
      'nav.settings': 'Settings',
      'nav.logout': 'Logout',
      'settings.title': 'Settings',
      'settings.preferences': 'Preferences',
      'settings.application': 'Application',
      'settings.support': 'Support',
      'settings.language': 'Language',
      'settings.change_language': 'Change application language',
      'settings.notifications': 'Notifications',
      'settings.notifications_desc': 'Configure alerts',
      'settings.downloads': 'Downloads',
      'settings.downloads_desc': 'Manage offline documents',
      'settings.security': 'Security',
      'settings.security_desc': 'Change password',
      'settings.theme': 'Theme',
      'settings.theme_desc': 'Dark/Light mode',
      'settings.help': 'Help',
      'settings.help_desc': 'Support and FAQ',
      'settings.about': 'About',
      'settings.about_desc': 'Version and information',
      'greet.hello': 'Hello',
      'dashboard.subtitle': 'Here is the summary of your trip.',
      'documents.title': 'Documents & Itinerary',
      'documents.subtitle': 'Manage your travel documents',
      'profile.title': 'My Profile',
      'profile.subtitle': 'View your information',
      'common.retry': 'Retry',
      'common.loading': 'Loading...',
      'error.load_failed': 'Error loading data',
      'error.generic': 'Error',
      'dashboard.no_active_title': 'No active trips found',
      'dashboard.no_active_subtitle': 'No active trip was found for you',
      'dashboard.trip_type': 'Organized trip',
      'info.client': 'Client',
      'info.email': 'Email',
      'info.phone': 'Phone',
      'trip.program': 'Trip schedule',
      'profile.active_traveler': 'Active traveler',
      'profile.active_trips': 'Active Trips',
      'profile.days': 'Days',
      'profile.folders': 'Folders',
      'profile.last_active_trip': 'Last active trip',
      'dossiers.results_days': '{count} day{plural} found',
      'dossiers.filtered': 'Filtered',
      'dossiers.id': 'ID',
      'dossiers.subfolders_count': '{count} folder{plural}',
      'dossiers.docs_suffix': 'docs',
      'download.preparing': 'Preparing download...',
      'download.unavailable': 'Unable to access the downloads folder',
      'download.completed': 'File downloaded: {file}',
      'download.open_folder_fail': 'Unable to open the tripbuilder folder',
      'download.alt_try': 'Trying alternative download...',
      'share.preparing': 'Preparing share...',
      'share.success': 'Document shared successfully',
      'share.error': 'Error while sharing: {error}',
      'share.alt_error': 'Alternate sharing error: {error}',
      'auth.logout': 'Logout',
      'auth.logout_confirm': 'Are you sure you want to logout?',
      'password.screen_title': 'Account Security',
      'password.security_tip': 'For your security, please set a new password',
      'password.change_title': 'Change Password',
      'password.current': 'Current password',
      'password.current_hint': 'Enter your current password',
      'password.new': 'New password',
      'password.new_hint': 'Choose a secure password',
      'password.confirm': 'Confirm new password',
      'password.confirm_hint': 'Repeat your new password',
      'password.error_current_required': 'Please enter your current password',
      'password.error_new_required': 'Please enter a new password',
      'password.error_min_length': 'Password must be at least 6 characters',
      'password.error_confirm_required': 'Please confirm the new password',
      'password.error_mismatch': 'Passwords do not match',
      'password.changing': 'Changing...',
      'password.confirm_change': 'Confirm change',
      'password.changed_success': 'Password changed successfully',
    },
  };

  String t(String key, {Map<String, String>? params}) {
    final values =
        _localizedValues[locale.languageCode] ?? _localizedValues['fr']!;
    String text = values[key] ?? key;
    if (params != null) {
      params.forEach((k, v) {
        text = text.replaceAll('{$k}', v);
      });
    }
    return text;
  }
}

extension BuildContextLocalization on BuildContext {
  AppLocalizations l10n(Locale locale) => AppLocalizations(locale);
}
